url: https://hanabinosensu.github.io  # no trailing slash
baseurl: ""

exclude:
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
# - .sass-cache/
# - .jekyll-cache/
# - gemfiles/
# - node_modules/
# - vendor/bundle/
# - vendor/cache/
# - vendor/gems/
# - vendor/ruby/

defaults:
  - scope:
      path: news/_posts
    values:
      layout: news
      permalink: /news/:title
